<a href="https://colab.research.google.com/github/joynaomi81/Language_Detection_Model_with_NLP/blob/main/Language_Detection_model_with_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Language Detection.csv')

In [ ]:
data.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [ ]:
data.columns

Index(['Text', 'Language'], dtype='object')

In [ ]:
data.describe()

Text Language
count            10337    10337
unique           10267       17
top     Jag är ledsen.  English
freq                 3     1385

In [ ]:
data.shape

(10337, 2)

In [ ]:
data['Language'].value_counts()

English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: Language, dtype: int64

In [ ]:
import string
import re
import codecs
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [ ]:
for char in string.punctuation:
  print(char,end='')
  translate_table = dict((ord(char),None)for char in string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [ ]:
x= data['Text']
y=data['Language']

In [ ]:
import re
data_list = []
for text in x:
    text = text.lower()
    text = re.sub(r'\d+','',text)
    data_list.append(text)


In [ ]:
x= data_list

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33,random_state=43)

In [ ]:
len(x_train)

6925

In [ ]:
len(x_test)

3412

In [ ]:
from sklearn import feature_extraction, linear_model
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
vectorizer = feature_extraction.text.TfidfVectorizer(ngram_range=(1, 3), analyzer='char')
pipe_lr_r13 = Pipeline([
    ('vectorizer', vectorizer),
    ('clf', linear_model.LogisticRegression())
])


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

lang_clf = Pipeline([('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])
lang_clf.fit(x_train, y_train)


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [ ]:
pipe_lr_r13.fit(x_train, y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [ ]:
y_predicted = pipe_lr_r13.predict(x_test)

In [ ]:

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score


In [ ]:
from numpy.matrixlib.defmatrix import matrix
matrix = metrics.confusion_matrix(y_test,y_predicted)
print('Confusion matrix: \n',matrix)

Confusion matrix: 
 [[183   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 131   0   2   1   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0 163   4   3   3   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0   1 459   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 327   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   1   3   0   0 165   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 130   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  24   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   3   0   0   0 226   0   0   2   0   3   0   0   0]
 [  0   0   0   0   0   0   0   0   0 130   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0 205   0   0   0   0   0   0]
 [  0   0   0   0   4   1   0   0   1   0   0 245   0   3   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0 209   0   0   0   1]
 [  0   0   0   0   1   0   0   0   1   0   0   2   0 272

In [ ]:
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

      Arabic       1.00      1.00      1.00       183
      Danish       0.98      0.97      0.98       135
       Dutch       0.98      0.93      0.95       175
     English       0.98      1.00      0.99       461
      French       0.96      1.00      0.98       328
      German       0.98      0.98      0.98       169
       Greek       1.00      1.00      1.00       130
       Hindi       1.00      1.00      1.00        24
     Italian       0.99      0.96      0.98       235
     Kannada       1.00      1.00      1.00       130
   Malayalam       1.00      1.00      1.00       206
  Portugeese       0.98      0.96      0.97       254
     Russian       1.00      0.99      1.00       211
     Spanish       0.97      0.98      0.98       278
    Sweedish       0.98      0.99      0.99       213
       Tamil       1.00      1.00      1.00       137
     Turkish       0.99      1.00      0.99       143

    accuracy              

In [ ]:
print(accuracy_score(y_test, y_predicted))

0.984759671746776


In [ ]:
!pip install langdetect

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 20.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993224 sha256=3a92d7d442c79ae5ae436b220905cb0b793d4f50d7f6c49f40f1c0276d2d38a3
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect


Text random language phrase. 'How are you?'

In [ ]:
#English
lang_clf.predict(['How are you?'])

array(['English'], dtype=object)

In [ ]:
#German
lang_clf.predict(['Wie geht es dir?'])

array(['German'], dtype=object)

In [ ]:
#French
lang_clf.predict(['Comment allez-vous?'])

array(['French'], dtype=object)

In [ ]:
#Danish
lang_clf.predict(['Hvordan har du det?'])

array(['Danish'], dtype=object)