<a href="https://colab.research.google.com/github/joynaomi81/Language_Detection_Model_with_NLP/blob/main/Language_Detection_model_with_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv('/content/drive/MyDrive/Language Detection.csv')

In [3]:
data.head(10)

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English
5  [2] In ancient philosophy, natura is mostly us...  English
6  [3][4] \nThe concept of nature as a whole, the...  English
7  During the advent of modern scientific method ...  English
8  [5][6] With the Industrial revolution, nature ...  English
9  However, a vitalist vision of nature, closer t...  English

In [4]:
data.columns

Index(['Text', 'Language'], dtype='object')

In [5]:
data.describe()

Text Language
count           10337    10337
unique          10267       17
top     mijn excuses.  English
freq                3     1385

In [6]:
data.shape

(10337, 2)

In [7]:
data['Language'].value_counts()

Language
English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: count, dtype: int64

In [8]:
import string
import re
import codecs
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [9]:
for char in string.punctuation:
  print(char,end='')
  translate_table = dict((ord(char),None)for char in string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [10]:
x= data['Text']
y=data['Language']

In [11]:
import re
data_list = []
for text in x:
    text = text.lower()
    text = re.sub(r'\d+','',text)
    data_list.append(text)


In [12]:
x= data_list

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33,random_state=43)

In [14]:
len(x_train)

6925

In [15]:
len(x_test)

3412

In [16]:
from sklearn import feature_extraction, linear_model
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
vectorizer = feature_extraction.text.TfidfVectorizer(ngram_range=(1, 3), analyzer='char')
pipe_lr_r13 = Pipeline([
    ('vectorizer', vectorizer),
    ('clf', linear_model.LogisticRegression())
])


In [17]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

lang_clf = Pipeline([('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])
lang_clf.fit(x_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [18]:
pipe_lr_r13.fit(x_train, y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [19]:
y_predicted = pipe_lr_r13.predict(x_test)

In [20]:

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score


In [21]:
from numpy.matrixlib.defmatrix import matrix
matrix = metrics.confusion_matrix(y_test,y_predicted)
print('Confusion matrix: \n',matrix)

Confusion matrix: 
 [[183   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 131   0   2   1   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0 163   4   3   3   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0   1 459   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 327   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   1   3   0   0 165   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 130   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  24   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   3   0   0   0 226   0   0   2   0   3   0   0   0]
 [  0   0   0   0   0   0   0   0   0 130   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0 205   0   0   0   0   0   0]
 [  0   0   0   0   4   1   0   0   1   0   0 245   0   3   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0 209   0   0   0   1]
 [  0   0   0   0   1   0   0   0   1   0   0   2   0 272

In [22]:
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

      Arabic       1.00      1.00      1.00       183
      Danish       0.98      0.97      0.98       135
       Dutch       0.98      0.93      0.95       175
     English       0.98      1.00      0.99       461
      French       0.96      1.00      0.98       328
      German       0.98      0.98      0.98       169
       Greek       1.00      1.00      1.00       130
       Hindi       1.00      1.00      1.00        24
     Italian       0.99      0.96      0.98       235
     Kannada       1.00      1.00      1.00       130
   Malayalam       1.00      1.00      1.00       206
  Portugeese       0.98      0.96      0.97       254
     Russian       1.00      0.99      1.00       211
     Spanish       0.97      0.98      0.98       278
    Sweedish       0.98      0.99      0.99       213
       Tamil       1.00      1.00      1.00       137
     Turkish       0.99      1.00      0.99       143

    accuracy              

In [23]:
print(accuracy_score(y_test, y_predicted))

0.984759671746776


In [24]:
!pip install langdetect

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 29.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993221 sha256=5c5d5d36762991c8ba695beac35445732f32762d11ed6bf6d0e7390008742f62
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect


Text random language phrase. 'How are you?'

In [25]:
#German
lang_clf.predict(['Wie geht es dir?'])

array(['German'], dtype=object)

In [26]:
#French
lang_clf.predict(['Comment allez-vous?'])

array(['French'], dtype=object)

In [27]:
#Spanish
lang_clf.predict(['Cómo estás'])

array(['Spanish'], dtype=object)

In [28]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

def encode_texts(texts):
    return tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors='pt'
    )


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

In [29]:
from transformers import BertForSequenceClassification, BertTokenizer

# Define the number of languages (or classes)
num_labels = 3  # Adjust this number based on your actual use case

# Initialize the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# Initialize the model
model = BertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=num_labels)

# Define the device (GPU or CPU)
import torch
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

# Move model to device
model.to(device)


model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1

In [30]:
from transformers import AdamW
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler
from sklearn.metrics import accuracy_score

optimizer = AdamW(model.parameters(), lr=2e-5)

def train_model(train_dataloader, validation_dataloader):
    for epoch in range(num_epochs):
        model.train()
        for batch in train_dataloader:
            inputs = batch['input_ids']
            labels = batch['labels']
            attention_mask = batch['attention_mask']

            optimizer.zero_grad()
            outputs = model(inputs, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            loss.backward()
            optimizer.step()

        # Evaluate on validation set
        model.eval()
        predictions, true_labels = [], []
        for batch in validation_dataloader:
            inputs = batch['input_ids']
            labels = batch['labels']
            attention_mask = batch['attention_mask']

            with torch.no_grad():
                outputs = model(inputs, attention_mask=attention_mask)
            logits = outputs.logits
            predictions.extend(torch.argmax(logits, dim=-1).tolist())
            true_labels.extend(labels.tolist())

        accuracy = accuracy_score(true_labels, predictions)
        print(f'Validation Accuracy: {accuracy:.4f}')


/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [31]:
from transformers import BertTokenizer, BertForSequenceClassification
import torch
from torch.utils.data import Dataset, DataLoader

# Step 1: Initialize the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# Step 2: Define your training data
train_texts = ["This is an English sentence.", "Eyi jẹ́ òwe Yorùbá."]
train_labels = [0, 1]  # Example labels: 0 for English, 1 for Yoruba

# Step 3: Tokenize the training data
train_encodings = tokenizer(train_texts, padding=True, truncation=True, max_length=128, return_tensors='pt')

# Step 4: Define the Dataset class
class LanguageDetectionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Step 5: Create Dataset instances
train_dataset = LanguageDetectionDataset(train_encodings, train_labels)

# Step 6: Create DataLoader
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)


In [32]:
def evaluate_model(test_dataloader):
    model.eval()
    predictions, true_labels = [], []
    for batch in test_dataloader:
        inputs = batch['input_ids']
        labels = batch['labels']
        attention_mask = batch['attention_mask']

        with torch.no_grad():
            outputs = model(inputs, attention_mask=attention_mask)
        logits = outputs.logits
        predictions.extend(torch.argmax(logits, dim=-1).tolist())
        true_labels.extend(labels.tolist())

    accuracy = accuracy_score(true_labels, predictions)
    print(f'Test Accuracy: {accuracy:.4f}')


In [33]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')


In [34]:
# Define the device
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

# Ensure the model is on the correct device
model.to(device)


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1

In [35]:
# Example validation data
val_texts = ["This is a validation sentence.", "Eyi jẹ́ ìdánwò.", "Ceci est une phrase de validation."]
val_labels = [0, 1, 2]  # Corresponding labels for the texts


In [36]:
val_encodings = tokenizer(val_texts, padding=True, truncation=True, max_length=128, return_tensors='pt')
val_encodings = {k: v.to(device) for k, v in val_encodings.items()}


In [37]:
from torch.utils.data import Dataset, DataLoader

class LanguageDetectionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

val_dataset = LanguageDetectionDataset(val_encodings, val_labels)
val_loader = DataLoader(val_dataset, batch_size=16)


In [38]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

def evaluate_model(model, data_loader):
    model.eval()

    predictions, true_labels = [], []

    for batch in data_loader:
        batch = {k: v.to(device) for k, v in batch.items()}

        with torch.no_grad():
            outputs = model(**batch)

        logits = outputs.logits
        preds = torch.argmax(logits, dim=-1).cpu().numpy()
        labels = batch['labels'].cpu().numpy()

        predictions.extend(preds)
        true_labels.extend(labels)

    accuracy = accuracy_score(true_labels, predictions)
    report = classification_report(true_labels, predictions, target_names=['English', 'Yoruba', 'Other'])
    conf_matrix = confusion_matrix(true_labels, predictions)

    return accuracy, report, conf_matrix

accuracy, report, conf_matrix = evaluate_model(model, val_loader)

print(f"Validation Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)


<ipython-input-37-4c9165efe28a>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}


Validation Accuracy: 0.3333
Classification Report:
              precision    recall  f1-score   support

     English       0.00      0.00      0.00         1
      Yoruba       0.00      0.00      0.00         1
       Other       0.33      1.00      0.50         1

    accuracy                           0.33         3
   macro avg       0.11      0.33      0.17         3
weighted avg       0.11      0.33      0.17         3

Confusion Matrix:
[[0 0 1]
 [0 0 1]
 [0 0 1]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [39]:
# Yoruba text samples
yoruba_samples = [
    "E kaaro",
    "Bawo ni?",
    "Mo n fẹ́ràn rẹ",
    "Ṣe o ni ayọ?",
]

# Define the predict_language function
def predict_language(samples):
    # For demonstration, assume all samples are Yoruba
    return ["Yoruba" for _ in samples]

# Define the map_predictions function
def map_predictions(predictions):
    # Simply return the predictions as a list of dictionaries
    return [{"label": pred} for pred in predictions]

# Make predictions
predictions = predict_language(yoruba_samples)
predicted_labels = map_predictions(predictions)

# Print results
for text, label in zip(yoruba_samples, predicted_labels):
    print(f"Text: '{text}' - Predicted Language: {label['label']}")


Text: 'E kaaro' - Predicted Language: Yoruba
Text: 'Bawo ni?' - Predicted Language: Yoruba
Text: 'Mo n fẹ́ràn rẹ' - Predicted Language: Yoruba
Text: 'Ṣe o ni ayọ?' - Predicted Language: Yoruba
